# Generated by Django 3.2.14 on 2022-12-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20221212_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='areas',
        ),
        migrations.AddField(
            model_name='cv',
            name='jobs',
            field=models.ManyToManyField(related_name='cvs', to='jobs.Job'),
        ),
    ]
