# Generated by Django 3.2.14 on 2022-12-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20221213_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='behance',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='portfolio_url',
        ),
        migrations.AddField(
            model_name='cv',
            name='social_links',
            field=models.TextField(blank=True),
        ),
    ]
